language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: surge
  project: ./build/
  domain: loremoji.app.pavey.dev 
  skip_cleanup: true
on:
  branch: master
before_install:
  - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${FA_TOKEN}" >> ~/.npmrc
